// <auto-generated />
using BEndClientes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BEndClientes.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20220213031713_DBInitial1.0")]
    partial class DBInitial10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BEndClientes.Models.Cliente", b =>
                {
                    b.Property<decimal>("identificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(11,0)")
                        .HasColumnName("Identificacion")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("idtipodocref")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("idtipodoc");

                    b.Property<string>("nombrecompleto")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NombreCompleto");

                    b.Property<int>("proveedores")
                        .HasColumnType("integer")
                        .HasColumnName("Proveedores");

                    b.Property<string>("razonsocial")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("RazonSocial");

                    b.Property<int>("ventas")
                        .HasColumnType("integer")
                        .HasColumnName("Ventas");

                    b.HasKey("identificacion");

                    b.HasIndex("idtipodocref");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BEndClientes.Models.TipoDocumento", b =>
                {
                    b.Property<string>("idtipodoc")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("idtipodoc");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Descripcion");

                    b.HasKey("idtipodoc");

                    b.ToTable("TipoDocumentos");
                });

            modelBuilder.Entity("BEndClientes.Models.Cliente", b =>
                {
                    b.HasOne("BEndClientes.Models.TipoDocumento", "idtipodoc")
                        .WithMany("Clientes")
                        .HasForeignKey("idtipodocref");

                    b.Navigation("idtipodoc");
                });

            modelBuilder.Entity("BEndClientes.Models.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
